### ISSUE TITLE
placeholders in post_type slug

### ISSUE THREAD

**Issue by maketheboat** [KLicheR/wp-polylang-translate-rewrite-slugs#3]
Hey - great plugin..

I have an issue - I'd like my custom post_type slugs to contain variable placeholders - which are taxonomy terms - for example:

```
 // Add translation for "property".
 $post_type_translated_slugs['property'] = array(
            'en' => 'property/%property_type%/%location%',
            'nl' => 'eigendom/%property_type%/%location%',
 );
```

I've hacked your "post_type_link_filter" filter - and the slugs are displaying correctly:

```
// type ##
if ( false !== strpos( $post_link, '%property_type%' ) ) {
   $get_term = get_the_terms( $post->ID, 'property_type' );
   if ( $get_term && is_array( $get_term ) ) { 
      $post_link = str_replace( '%property_type%', array_pop( $get_term )->slug, $post_link );
   }
}
```

However, all posts 404 when viewed - I've tried flushing the permalinks, but no joy.

Am I going about this the wrong way - is there an easier method to pass and correct those placeholders?

Cheers!

Q

**Comment by Jones-S** [comment]
I would also like to have custom post_type slugs to be rewritten.
I used the string translations of the [polylang](https://polylang.pro/) plugin, but so far I could only translate the slugs but set no placeholders:
<img width="1293" alt="image" src="https://user-images.githubusercontent.com/7059580/47944353-301a7d00-defb-11e8-8471-3f533b81d576.png">

I am absolutely not sure if I am at the right place here, I don't even see if your repository is somehow linked to polylang.
I see that I would like to achieve the exact thing asked in the question above.

I would like to have permalink structures like this:
`company/media/%year%/%postname%` for my custom post type.

So I would be extremely glad if you could give me hint to the right direction...
Thank you in advance.
