### ISSUE TITLE
It does not work with Polylang 1.9

### ISSUE THREAD

**Issue by ghost** [KLicheR/wp-polylang-translate-rewrite-slugs#41]

**Comment by grappler** [comment]
You could switch to the pro version which supports this feature.

**Comment by StefanoVuerich** [comment]
+1

**Comment by strarsis** [comment]
@KLicheR: Is this plugin still maintained? :)

**Comment by KLicheR** [comment]
Hey folks,
I haven't worked on this for years now. I would be happy if it help someone to continue the work by forking it but I don't have time to work on it myself.
